services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: my-react-frontend-app
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: my-node-backend-app
    ports:
      - '8080:8080'
    environment:
      - JWT_SECRET=BLABLABLA
      - JWT_EXPIRES_IN=1d
      - DB_DIALECT=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=test_docker_kubernetes
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: my-mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: my-mongo-express
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=user
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb


  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: my-mongo-express
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_OPTIONS_EDITORTHEME=default
  #     - ME_CONFIG_REQUEST_SIZE=100kb
  #     - ME_CONFIG_SITE_BASEURL=/
  #     - ME_CONFIG_SITE_COOKIESECRET=cookiesecret
  #     - ME_CONFIG_SITE_SESSIONSECRET=sessionsecret
  #     - ME_CONFIG_SITE_SSL_ENABLED=false
  #     - ME_CONFIG_SITE_SSL_CRT_PATH=
  #     - ME_CONFIG_SITE_SSL_KEY_PATH=
  #   depends_on:
  #     - mongodb


volumes:
  mongo-data: